apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: portic-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      volumes:
      - name: jenkins-pvc
        persistentVolumeClaim:
          claimName: jenkins-pvc
      containers:
        - name: container-0
          image: default-route-openshift-image-registry.apps-crc.testing/portic-devops/jenkins:2.319.2-alpine
          imagePullPolicy: Always
          ports:
            - name: http-port
              containerPort: 8080
            - name: jnlp-port
              containerPort: 50000
          volumeMounts:
          - mountPath: /var/jenkins_home
            name: jenkins-pvc
