node {
	checkout scm
	sh docker login 
	docker.withRegistry('image-registry.openshift-image-registry.svc:5000/','portic_image_puller'){
		def customImage = docker.build("portic-devops/tomcat8-portic:${env.BUILD_ID}")
		customImage.push()
	}
}

