apiVersion: v1
kind: Service
metadata:
  name: artifactory
  namespace: portic-devops
spec:
  selector:
    app: artifactory
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: 8081-tcp
    protocol: TCP
    port: 8081
    targetPort: 8081
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.
    nodePort:
