#FROM jenkins/jenkins:2.332.2-jdk11
FROM jenkins/jenkins:lts-alpine-jdk11
USER root
RUN sed -i 's,3.15,3.14,g' /etc/apk/repositories
#RUN apk add maven nodejs 
RUN apk add  --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/v3.14/main/ && apk add podman-docker=3.2.3-r1 
COPY DEPLOYMENT/ca.crt /usr/local/share/ca-certificates/
RUN update-ca-certificates
#RUN useradd -m docker && sudo usermod -a -G sudo jenkins && sudo usermod -a -G sudo docker
COPY wrapper.sh /usr/local/sbin/wrapper.sh
#USER jenkins
ENTRYPOINT /usr/local/sbin/wrapper.sh
