#FROM jenkins/jenkins:2.332.2-jdk11
FROM jenkins/jenkins:centos7-jdk8
USER root
RUN yum install -y podman-docker ca-certificates > /dev/null
COPY DEPLOYMENT/ca.crt /etc/pki/ca-trust/source/anchors/
RUN update-ca-trust && rm -f /etc/sub* && touch /etc/sub{u,g}id && usermod --add-subuids 10000-75535 $(whoami) && usermod --add-subgids 10000-75535 $(whoami) 
#RUN useradd -m docker && sudo usermod -a -G sudo jenkins && sudo usermod -a -G sudo docker
COPY wrapper.sh /usr/local/sbin/wrapper.sh
#USER jenkins
ENTRYPOINT /usr/local/sbin/wrapper.sh
