FROM jenkins/jenkins:2.332.2-jdk11
#FROM jenkins/jenkins:alpine-jdk11
USER root
RUN apt-get update && apt-get install -qq -y lsb-release curl sudo kmod iptables maven nodejs npm git  uidmap 
RUN apt install -y containerd
#RUN curl -fsSLo /usr/share/keyrings/docker-archive-keyring.asc \
  #https://download.docker.com/linux/debian/gpg
#RUN echo "deb [arch=$(dpkg --print-architecture) \
#  signed-by=/usr/share/keyrings/docker-archive-keyring.asc] \
#  https://download.docker.com/linux/debian \
#  $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
#RUN apt install -y docker-compose
COPY DEPLOYMENT/ca.crt /usr/local/share/ca-certificates/
#RUN useradd -m docker && sudo usermod -a -G sudo jenkins && sudo usermod -a -G sudo docker
RUN sudo usermod -a -G sudo jenkins 

RUN echo "%sudo ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

COPY wrapper.sh /usr/local/sbin/wrapper.sh
RUN cd /tmp/ 
RUN update-ca-certificates

USER jenkins

RUN  curl -fsSL https://get.docker.com/rootless > /tmp/rootless.sh && chmod a+x /tmp/rootless.sh && /tmp/rootless.sh


#USER jenkins
ENTRYPOINT /usr/local/sbin/wrapper.sh
